### ISSUE TITLE
Using deploy rock and selecting sensor option still runs server

### ISSUE THREAD

**Issue by tfplenum** [tfplenum/rock#13]
<a href="https://github.com/grantcurell"><img src="https://avatars2.githubusercontent.com/u/1595564?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grantcurell](https://github.com/grantcurell)**
_Monday Jan 01, 2018 at 23:23 GMT_
_Originally opened as https://github.com/grantcurell/rock/issues/34_

----

Haven't looked into it at all, but when I ran deploy_rock.sh and selected sensor, it still ran the server.yml code. I'm not sure why. I think it has something to do with the line `ansible-playbook site.yml --limit sensors` not working the way I anticipated.

**Comment by grantcurell** [comment]
<a href="https://github.com/littletone2002"><img src="https://avatars3.githubusercontent.com/u/10156672?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [littletone2002](https://github.com/littletone2002)**
_Tuesday Jan 02, 2018 at 07:09 GMT_

----

The `--limit` option doesn't work the way we think it does, see: 
[https://github.com/ansible/ansible/issues/16851]()

the `--limit sensor` option, limits which hosts get targeted, ie, it looks to see what ips/dns names are associated with sensor, in our case rock simplerockbuild.simplerock.lan and says I will only run roles in which this name is apart of. Since that name is associated with all the roles in the inventory file, they all run. .

**Comment by dwharve** [comment]
Changed inventory to now have specific roles per role group (servers,sensors). Issue should be resolved.
