### ISSUE TITLE
Need to figure out GeoIP

### ISSUE THREAD

**Issue by tfplenum** [tfplenum/rock#2]
End State: Kibana should properly display GeoIP information for both Bro and Suricata

Edit Notes: Removed all old issue text and replaced it with the end state.

**Comment by grantcurell** [comment]
<a href="https://github.com/grantcurell"><img src="https://avatars2.githubusercontent.com/u/1595564?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grantcurell](https://github.com/grantcurell)**
_Monday Jan 01, 2018 at 23:20 GMT_

----

My temporary solution to this problem was to move the GeoIP task to the bro role. That appears to be the only place it is currently used. We should perform a review and see if there is anywhere else we should be using it.

**Comment by grantcurell** [comment]
<a href="https://github.com/dcode"><img src="https://avatars1.githubusercontent.com/u/171574?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dcode](https://github.com/dcode)**
_Tuesday Jan 02, 2018 at 21:23 GMT_

----

The GeoIP tasks above update the GeoIP v1 MaxMind databases which are used by Bro. Logstash uses the GeoIP v2 databases and uses its internal package db that is snapshotted at build time. See [logstash docs](https://www.elastic.co/guide/en/logstash/current/plugins-filters-geoip.html) on more information on how that works.

**Comment by todd8152** [comment]
Do we really need to do GeoIP lookups twice?  Once with Bro and once with Logstash?

**Comment by grantcurell** [comment]
No, we should just do it in Logstash. We need to go look at how this is being done and make sure this functionality is there.
