### ISSUE TITLE
Need to test Kafka and Zookeeper and containerize it on the new version of Rock

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#61]
Right now Kafka runs as a regular installation. We need to pull it down from the current container source and then make sure it integrates correctly with Logstash.

**Comment by kwilson7770** [comment]
Apache does not currently have an official docker image. Found third party built versions:

https://hub.docker.com/r/wurstmeister/kafka/
https://hub.docker.com/r/spotify/kafka/

The problem is that it would require trusting third part folks to create docker images properly and not install anything malicious like backdoors

**Comment by dwharve** [comment]
Check out the DockerFile and see if you can't build the image from that

**Comment by kwilson7770** [comment]
Ended up just making the image and container using the https://copr.fedorainfracloud.org/coprs/g/rocknsm/rocknsm-2.1/ repo to install the software.  Thanks @dwharve, that lead me in the right direction. The docker containers work in https://github.com/tfplenum/rock/pull/83
